<a href="https://colab.research.google.com/github/HannahWang1110/1/blob/master/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a=3

In [2]:
a

3

In [53]:
!pip3 install torch torchvision

In [0]:
import torch

In [55]:
x=torch.empty(1,3)
print(x)

tensor([[8.3948e-36, 0.0000e+00, 2.8026e-45]])


In [5]:
x.size()

torch.Size([1, 3])

In [0]:
b=torch.Tensor(3,5)

In [8]:
print(b)

tensor([[1.1216e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00,        nan],
        [0.0000e+00, 1.3733e-14, 6.4069e+02, 4.3066e+21, 1.1824e+22],
        [4.3066e+21, 6.3828e+28, 3.8016e-39, 4.3205e-05, 0.0000e+00]])


In [0]:
b=torch.Tensor(3,5,6)

In [10]:
b

tensor([[[ 2.8116e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  2.8114e-37,  0.0000e+00,  2.8114e-37,
           0.0000e+00],
         [ 2.8115e-37,  0.0000e+00,  0.0000e+00,  0.0000e+00,  7.0335e-24,
           1.3936e+05],
         [ 1.5838e-30,  1.4610e+11,  1.8876e+38,  1.6725e-36,  2.8122e-32,
           2.4613e-38],
         [ 2.8115e-37,  0.0000e+00,  2.8115e-37,  0.0000e+00,  2.8115e-37,
           0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  5.1887e-04,  3.7275e-43,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  8.0673e+31,  4.5828e-41,  9.2197e-41,
           0.0000e+00],
         [-2.9941e+16,  4.5828e-41,  2.4928e+37,  4.5828e-41,  2.4928e+37,
           4.5828e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00]],

      

In [11]:
b.size()

torch.Size([3, 5, 6])

In [0]:
c=torch.IntTensor([1,1,3])

In [14]:
c

tensor([1, 1, 3], dtype=torch.int32)

In [15]:
c.size()

torch.Size([3])

In [0]:
dc=torch.IntTensor(1)

In [24]:
dc

tensor([86097336], dtype=torch.int32)

In [21]:
dc.size()

torch.Size([1])

In [35]:
x.fill_[(5.33),dtype=torch.int32]

SyntaxError: ignored

In [38]:
x.mean()

tensor(5.3300)

In [39]:
x

tensor([[5.3300, 5.3300, 5.3300]])

In [40]:
x.std()

tensor(0.)

In [41]:
x.numpy()

array([[5.33, 5.33, 5.33]], dtype=float32)

In [0]:
k=torch.tensor([[1,1,3],[2,2,3],[3,4,2]])
j=torch.tensor([[3,1,3],[3,4,2]])

In [43]:
k.size()

torch.Size([3, 3])

In [44]:
j.size()

torch.Size([2, 3])

In [0]:
jj=j.t()

In [48]:
k@jj

tensor([[13, 13],
        [17, 20],
        [19, 29]])

In [0]:
kk=torch.mm(k,jj)

In [50]:
print(kk)

tensor([[13, 13],
        [17, 20],
        [19, 29]])


In [56]:
k.view(1,9)

tensor([[1, 1, 3, 2, 2, 3, 3, 4, 2]])

In [59]:
k.unsqueeze_(0)

tensor([[[1, 1, 3],
         [2, 2, 3],
         [3, 4, 2]]])

In [0]:
import numpy as np

In [0]:
x1=np.asarray([[1,2,3],[4,5,6]])

In [0]:
x2=np.zeros((2,2))

In [69]:
x2

array([[0., 0.],
       [0., 0.]])

In [73]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
x3=x1[None,:,:]
print(x3)

[[[1 2 3]
  [4 5 6]]]


In [85]:
x4=x1[:,:,None]
print(x4)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [88]:
print(x3.shape)

(1, 2, 3)


In [87]:
print(x4.shape)

(2, 3, 1)


In [89]:
print(x1.shape)

(2, 3)


In [0]:
c=torch.IntTensor([[1,2,3],[4,5,6]])

In [91]:
print(c)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [92]:
c.size()

torch.Size([2, 3])

In [93]:
c1=c.unsqueeze(0)
print(c1.size())

torch.Size([1, 2, 3])


In [94]:
c2=c.unsqueeze(2)
print(c2.size())

torch.Size([2, 3, 1])


In [95]:
print(c1)

tensor([[[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int32)


In [96]:
print(c2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]], dtype=torch.int32)
